---
title: "Data Science: Visualization"
output: html_document
---  

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```
This is HarvardX PH125.2x
Data Science: Visualization course. For more details on using R Markdown see <https://learning.edx.org/course/course-v1:HarvardX+PH125.2x+2T2021/home>.

# Section 1: Introduction to Data Visualization and Distributions

## Quantile-Quantile Plots
```{r QQ-plot}
# define x and z
library(tidyverse)
library(dslabs)
data(heights)
index <- heights$sex=="Male"
x <- heights$height[index]
z <- scale(x)

# proportion of data below 69.5
mean(x <= 69.5)

# calculate observed and theoretical quantiles
p <- seq(0.05, 0.95, 0.05)
observed_quantiles <- quantile(x, p)
theoretical_quantiles <- qnorm(p, mean = mean(x), sd = sd(x))

# make QQ-plot
plot(theoretical_quantiles, observed_quantiles)
abline(0,1)

# make QQ-plot with scaled values
observed_quantiles <- quantile(z, p)
theoretical_quantiles <- qnorm(p)
plot(theoretical_quantiles, observed_quantiles)
abline(0,1)

# make a table of category proportions
prop.table(table(heights$sex))
```